version: "3"

services: 
    vehiculo:
        container_name: vehiculo_service
        restart: always
        build: .
        ports: 
            - "3001:3000"
        environment: 
            - MONGO_URI=mongodb://mongo_vehiculos/mydatabase
        links: 
            - mongo_vehiculos        
    mongo_vehiculos:
        container_name: mongodb_vehiculos
        image: mongo
        ports: 
            - "27018:27017"