version: '3'
services:
    estancia:
        container_name: estancia_service
        restart: always
        build: ./estancia
        ports: 
            - "3002:3002"
        environment: 
            - MONGO_URI=mongodb://mongo_estancias/mydatabase
        links: 
            - mongo_estancias
        volumes: 
            - ./estancia:/usr/src/app   
    mongo_estancias:
        container_name: mongodb_estancias
        image: mongo
        ports: 
            - "27020:27017"
        logging: 
            driver: none

    tarifa:
        container_name: tarifa_service
        restart: always
        build: ./tarifas
        ports: 
            - "3000:3000"
        environment: 
            - MONGO_URI=mongodb://mongo_tarifa/mydatabase
        links: 
            - mongo_tarifa
        volumes: 
            - ./tarifas:/usr/src/app      
    mongo_tarifa:
        container_name: mongodb_tarifa
        image: mongo
        ports: 
            - "27018:27017"
        logging: 
            driver: none

    vehiculo:
        container_name: vehiculo_service
        restart: always
        build: ./vehiculos
        ports: 
            - "3001:3001"
        environment: 
            - MONGO_URI=mongodb://mongo_vehiculos/mydatabase
        links: 
            - mongo_vehiculos
        volumes: 
            - ./vehiculos:/usr/src/app     
    mongo_vehiculos:
        container_name: mongodb_vehiculos
        image: mongo
        ports: 
            - "27019:27017"
        logging: 
            driver: none

    saldos:
        container_name: saldos_service
        restart: always
        build: ./saldos
        ports: 
            - "3004:3004"
        environment: 
            - MONGO_URI=mongodb://mongo_saldos/mydatabase
        links: 
            - mongo_saldos
        volumes: 
            - ./saldos:/usr/src/app 
    mongo_saldos:
        container_name: mongodb_saldos
        image: mongo
        ports: 
            - "27021:27017"
        logging: 
            driver: none
    apidocs:
        container_name: apidocs_service
        restart: always
        build: ./apidoc
        ports: 
            - "3005:3005"
            
    user_auth:
        container_name: user_auth_service
        restart: always
        build: ./user
        ports: 
            - "3006:3006"
        environment: 
            - MONGO_URI=mongodb://mongo_user_auths/mydatabase
            - TOKEN_LIVE_TIME=24h
        links: 
            - mongo_user_auths
        volumes: 
            - ./user:/usr/src/app    
    mongo_user_auths:
        container_name: mongodb_user_auths
        image: mongo
        ports: 
            - "27022:27017"
        logging: 
            driver: none
