version: "3"

services: 
    tarifa:
        container_name: tarifa_service
        restart: always
        build: .
        ports: 
            - "3000:3000"
        environment: 
            - MONGO_URI=mongodb://mongo_tarifa/mydatabase
        links: 
            - mongo_tarifa        
    mongo_tarifa:
        container_name: mongodb_tarifa
        image: mongo
        ports: 
            - "27017:27017"
