version: "3"

services: 
    tarifa:
        container_name: tarifa_service
        restart: always
        build: .
        ports: 
            - "3000:3000"
        environment: 
            - MONGO_URI=mongodb://mongo/mydatabase
        links: 
            - mongo        
    mongo:
        container_name: mongodb
        image: mongo
        ports: 
            - "27017:27017"
